In [12]:
import torch
torch.__version__
torch.cuda.is_available()

#使每个cell中同时显示多个变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

**第4---**

初始化

In [34]:
a=torch.rand(5)
a
b=a
b

c=list([[1,5,2]])
c
a=torch.tensor([5,8])
a
a=torch.tensor(c)
d=a.numpy()
print('*'*100)
d
d=a.numpy().tolist()
d

tensor([0.6196, 0.5223, 0.4238, 0.6735, 0.1504])

tensor([0.6196, 0.5223, 0.4238, 0.6735, 0.1504])

[[1, 5, 2]]

tensor([5, 8])

****************************************************************************************************


array([[1, 5, 2]], dtype=int64)

[[1, 5, 2]]

In [49]:
a=torch.zeros(2,4,5)
b=torch.ones(2,3,4)
b
c=torch.eye(5)
b.size()
b.type()
b.shape
b.numel()




tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

torch.Size([2, 3, 4])

'torch.FloatTensor'

torch.Size([2, 3, 4])

24

transpose permute view reshape 

In [51]:
a=[
    [[1,1,1,1],
     [2,2,2,2],
     [3,3,3,3]],
    
    [[4,4,4,4],
     [5,5,5,5],
     [6,6,6,6]] 
]

a=torch.tensor(a)
a
a.shape

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6]]])

torch.Size([2, 3, 4])

In [54]:
b=a.permute(2,1,0)
b
b.shape

tensor([[[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]]])

torch.Size([4, 3, 2])

In [58]:
c=a.permute(2,0,1)
c
c.shape

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

torch.Size([4, 2, 3])

In [59]:
d=a.permute(0,2,1)
d
d.shape

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

torch.Size([2, 4, 3])

In [60]:
a

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6]]])

In [61]:
a.transpose(0,1)

tensor([[[1, 1, 1, 1],
         [4, 4, 4, 4]],

        [[2, 2, 2, 2],
         [5, 5, 5, 5]],

        [[3, 3, 3, 3],
         [6, 6, 6, 6]]])

In [62]:
a.transpose(0,2)

tensor([[[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]],

        [[1, 4],
         [2, 5],
         [3, 6]]])

In [63]:
a.numel()

24

In [64]:
a.view(3,8)

tensor([[1, 1, 1, 1, 2, 2, 2, 2],
        [3, 3, 3, 3, 4, 4, 4, 4],
        [5, 5, 5, 5, 6, 6, 6, 6]])

In [65]:
b.view(3,8) #permute或transpose后不能在view，因为不连续

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [66]:
b.reshape(3,8)

tensor([[1, 2, 3, 4, 5, 6, 1, 2],
        [3, 4, 5, 6, 1, 2, 3, 4],
        [5, 6, 1, 2, 3, 4, 5, 6]])

squese unsquese

In [70]:

 x = torch.rand(2,1,3)
 x.shape

y = x.squeeze(0)
y.shape

z = y.squeeze(2)
z.shape

o = y.squeeze(1) #又有删去dim=1的维度才有效
o.shape


torch.Size([2, 1, 3])

torch.Size([2, 1, 3])

torch.Size([2, 1, 3])

torch.Size([2, 3])

**第5----**